.PHONY: build clean all

build:
	cd ocaml-4.09.1-runtime; ./configure; make runtime
	cp ocaml-4.09.1-runtime/runtime/libcamlrun.a .
	cc -fPIC -Wall -I./ocaml-4.09.1-runtime/runtime -ltermcap -lm -ldl -o run main.c embed_out.c libcamlrun.a

clean:
	rm -rf run libcamlrun.a
	$(MAKE) -C ocaml-4.09.1-runtime/runtime clean
	$(MAKE) -C ocaml-4.09.1-runtime/stdlib clean
	$(MAKE) -C ocaml-4.09.1-runtime/tools clean

all: build
